-- MySQL Script generated by MySQL Workbench
-- sáb 01 set 2018 11:38:44 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`custo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`custo` (
  `idcusto` INT NOT NULL,
  `preco` FLOAT NULL,
  PRIMARY KEY (`idcusto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pais` (
  `idPais` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `idEstado` INT NOT NULL,
  `idPais` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`),
  INDEX `fk_Estado_Pais1_idx` (`idPais` ASC),
  CONSTRAINT `fk_Estado_Pais1`
    FOREIGN KEY (`idPais`)
    REFERENCES `mydb`.`Pais` (`idPais`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `idCidade` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_idEstado` ASC),
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trajeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trajeto` (
  `idTrajeto` INT NOT NULL,
  `Cidade_origem` INT NOT NULL,
  `Cidade_destino` INT NOT NULL,
  INDEX `fk_trajeto_Cidade1_idx` (`Cidade_origem` ASC),
  INDEX `fk_trajeto_Cidade2_idx` (`Cidade_destino` ASC),
  PRIMARY KEY (`idTrajeto`),
  CONSTRAINT `fk_trajeto_Cidade1`
    FOREIGN KEY (`Cidade_origem`)
    REFERENCES `mydb`.`Cidade` (`idCidade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_trajeto_Cidade2`
    FOREIGN KEY (`Cidade_destino`)
    REFERENCES `mydb`.`Cidade` (`idCidade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passageiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passageiro` (
  `idPassageiro` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPassageiro`),
  INDEX `fk_Passageiro_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Passageiro_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo` (
  `idTipo` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Motorista` (
  `idMotorista` INT NOT NULL,
  `cnh` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idMotorista`),
  UNIQUE INDEX `cnh_UNIQUE` (`cnh` ASC),
  INDEX `fk_Motorista_Usuario1_idx` (`Usuario_idUsuario` ASC),
  UNIQUE INDEX `idMotorista_UNIQUE` (`idMotorista` ASC),
  CONSTRAINT `fk_Motorista_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carro` (
  `idCarro` INT NOT NULL,
  `placa` VARCHAR(8) NOT NULL,
  `Cor` VARCHAR(45) NOT NULL,
  `Tipo_idTipo` INT NOT NULL,
  `Motorista_idMotorista` INT NOT NULL,
  PRIMARY KEY (`idCarro`, `Motorista_idMotorista`),
  UNIQUE INDEX `idCarro_UNIQUE` (`idCarro` ASC),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC),
  INDEX `fk_Carro_Tipo1_idx` (`Tipo_idTipo` ASC),
  INDEX `fk_Carro_Motorista1_idx` (`Motorista_idMotorista` ASC),
  CONSTRAINT `fk_Carro_Tipo1`
    FOREIGN KEY (`Tipo_idTipo`)
    REFERENCES `mydb`.`Tipo` (`idTipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Carro_Motorista1`
    FOREIGN KEY (`Motorista_idMotorista`)
    REFERENCES `mydb`.`Motorista` (`idMotorista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avaliacao` (
  `idAvaliacao` INT NOT NULL,
  `nota` FLOAT NOT NULL,
  `Mensagem_idMensagem` INT NOT NULL,
  PRIMARY KEY (`idAvaliacao`),
  INDEX `fk_Avaliacao_Mensagem1_idx` (`Mensagem_idMensagem` ASC),
  CONSTRAINT `fk_Avaliacao_Mensagem1`
    FOREIGN KEY (`Mensagem_idMensagem`)
    REFERENCES `mydb`.`Mensagem` (`idMensagem`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Viagem` (
  `idViagem` INT NOT NULL,
  `custo_idcusto` INT NOT NULL,
  `trajeto_idTrajeto` INT NOT NULL,
  `Passageiro_idPassageiro` INT NOT NULL,
  `Carro_idCarro` INT NOT NULL,
  `Avaliacao_idAvaliacao` INT NOT NULL,
  PRIMARY KEY (`idViagem`, `custo_idcusto`, `trajeto_idTrajeto`),
  INDEX `fk_Viagem_custo1_idx` (`custo_idcusto` ASC),
  INDEX `fk_Viagem_trajeto1_idx` (`trajeto_idTrajeto` ASC),
  INDEX `fk_Viagem_Passageiro1_idx` (`Passageiro_idPassageiro` ASC),
  INDEX `fk_Viagem_Carro1_idx` (`Carro_idCarro` ASC),
  INDEX `fk_Viagem_Avaliacao1_idx` (`Avaliacao_idAvaliacao` ASC),
  CONSTRAINT `fk_Viagem_custo1`
    FOREIGN KEY (`custo_idcusto`)
    REFERENCES `mydb`.`custo` (`idcusto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Viagem_trajeto1`
    FOREIGN KEY (`trajeto_idTrajeto`)
    REFERENCES `mydb`.`trajeto` (`idTrajeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Viagem_Passageiro1`
    FOREIGN KEY (`Passageiro_idPassageiro`)
    REFERENCES `mydb`.`Passageiro` (`idPassageiro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Viagem_Carro1`
    FOREIGN KEY (`Carro_idCarro`)
    REFERENCES `mydb`.`Carro` (`idCarro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Viagem_Avaliacao1`
    FOREIGN KEY (`Avaliacao_idAvaliacao`)
    REFERENCES `mydb`.`Avaliacao` (`idAvaliacao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conversa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conversa` (
  `idConversa` INT NOT NULL,
  `Mensagem_idMensagem` INT NOT NULL,
  `Viagem_idViagem` INT NOT NULL,
  PRIMARY KEY (`idConversa`, `Mensagem_idMensagem`),
  INDEX `fk_Conversa_Viagem1_idx` (`Viagem_idViagem` ASC),
  CONSTRAINT `fk_Conversa_Viagem1`
    FOREIGN KEY (`Viagem_idViagem`)
    REFERENCES `mydb`.`Viagem` (`idViagem`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensagem` (
  `idMensagem` INT NOT NULL,
  `mensagem` TEXT NULL,
  `Conversa_idConversa` INT NOT NULL,
  PRIMARY KEY (`idMensagem`),
  INDEX `fk_Mensagem_Conversa1_idx` (`Conversa_idConversa` ASC),
  CONSTRAINT `fk_Mensagem_Conversa1`
    FOREIGN KEY (`Conversa_idConversa`)
    REFERENCES `mydb`.`Conversa` (`idConversa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `Mensagem_idMensagem` INT NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `nome_usuario_UNIQUE` (`nome_usuario` ASC),
  INDEX `fk_Usuario_Mensagem1_idx` (`Mensagem_idMensagem` ASC),
  CONSTRAINT `fk_Usuario_Mensagem1`
    FOREIGN KEY (`Mensagem_idMensagem`)
    REFERENCES `mydb`.`Mensagem` (`idMensagem`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `idTelefone` INT NOT NULL,
  `numero` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fk_Telefone_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Telefone_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Combustivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Combustivel` (
  `idCombustivel` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCombustivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_tem_combustivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_tem_combustivel` (
  `idCombustivel` INT NOT NULL,
  `idTipo` INT NOT NULL,
  PRIMARY KEY (`idCombustivel`, `idTipo`),
  INDEX `fk_Combustivel_has_Tipo_Tipo1_idx` (`idTipo` ASC),
  INDEX `fk_Combustivel_has_Tipo_Combustivel1_idx` (`idCombustivel` ASC),
  CONSTRAINT `fk_Combustivel_has_Tipo_Combustivel1`
    FOREIGN KEY (`idCombustivel`)
    REFERENCES `mydb`.`Combustivel` (`idCombustivel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Combustivel_has_Tipo_Tipo1`
    FOREIGN KEY (`idTipo`)
    REFERENCES `mydb`.`Tipo` (`idTipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
