# Generated by Django 2.1 on 2018-09-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('idmotorista', models.IntegerField(primary_key=True, serialize=False)),
                ('cnh', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'motorista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('idpassageiro', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'passageiro',
                'managed': False,
            },
        ),
    ]
