# Generated by Django 2.1 on 2018-09-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('idpassageiro', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'passageiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('idmotorista', models.AutoField(primary_key=True, serialize=False)),
                ('cnh', models.IntegerField(unique=True)),
                ('usuario_idusuario', models.ForeignKey(db_column='usuario_idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to='conta.AuthUser')),
            ],
            options={
                'db_table': 'motorista',
                'managed': True,
            },
        ),
    ]
