# Generated by Django 2.1 on 2018-09-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_tipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='idmotorista',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
