# Generated by Django 2.1 on 2018-08-14 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_tipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('\\w{4}\\d{4}', 'Insira um valor de placa válido', 'invalid')], verbose_name='Placa')),
                ('cor', models.CharField(choices=[('amarelo', 'Amarelo'), ('vermelho', 'Vermelho'), ('azul', 'Azul'), ('preto', 'Preto'), ('branco', 'branco')], max_length=10, verbose_name='Cor')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_tipos.Motorista', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Combustível')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Nome',
                'verbose_name_plural': 'Nomes',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_nome', models.CharField(max_length=40, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_nome', models.CharField(max_length=40, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelo',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.Marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.Modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Tipo de carro',
                'verbose_name_plural': 'Tipos de carros',
            },
        ),
        migrations.CreateModel(
            name='tipo_tem_combustivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.Combustivel', verbose_name='Combustivel')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.Tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo vs Combustivel',
                'verbose_name_plural': 'Tipo vs Combustivel',
            },
        ),
        migrations.AddField(
            model_name='carro',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.Tipo', verbose_name='Tipo do carro'),
        ),
    ]
