# Generated by Django 2.1 on 2018-08-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combustivel',
            options={'verbose_name': 'Combustível', 'verbose_name_plural': 'Combustível'},
        ),
    ]
