# Generated by Django 2.1 on 2018-09-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('idcarro', models.IntegerField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('cor', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'carro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('idcombustivel', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('preco', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'combustivel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idtipo', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTemCombustivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tipo_tem_combustivel',
                'managed': False,
            },
        ),
    ]
