# Generated by Django 2.1 on 2018-08-14 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Estado')),
                ('sigla', models.CharField(max_length=30, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='País')),
                ('sigla', models.CharField(max_length=30, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Trajeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidade_trajeto_destino', to='viagem.Cidade', verbose_name='Cidade Destino')),
                ('cidade_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidade_trajeto_origem', to='viagem.Cidade', verbose_name='Cidade Origem')),
            ],
            options={
                'verbose_name': 'Trajeto',
                'verbose_name_plural': 'Trajetos',
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Custo')),
                ('vagas', models.IntegerField(verbose_name='Vagas')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.Carro', verbose_name='Carro')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Passageiro')),
                ('trajeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.Trajeto', verbose_name='Tipos')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.Pais', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.Estado', verbose_name='Estado'),
        ),
    ]
