# Generated by Django 2.1 on 2018-09-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='custo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trajeto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='viagem',
            options={},
        ),
    ]
