# Generated by Django 2.1 on 2018-09-02 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0002_auto_20180902_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='custo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trajeto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='viagem',
            options={'managed': False},
        ),
    ]
