# Generated by Django 2.1 on 2018-09-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('idavaliacao', models.IntegerField(primary_key=True, serialize=False)),
                ('nota', models.FloatField()),
            ],
            options={
                'db_table': 'avaliacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('idconversa', models.IntegerField(primary_key=True, serialize=False)),
                ('mensagem_idmensagem', models.IntegerField()),
                ('viagem_idviagem', models.IntegerField()),
            ],
            options={
                'db_table': 'conversa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('idmensagem', models.IntegerField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('conversa_idconversa', models.IntegerField()),
            ],
            options={
                'db_table': 'mensagem',
                'managed': False,
            },
        ),
    ]
